### ISSUE TITLE
Resize Main node

### ISSUE THREAD

**Issue by feliperfpereira** [vasturiano/sunburst-chart#10]
Is there any way to resize the me main(first) node, I want to give more height to children's and less to main node
![sinergytech - ocs - google chrome](https://user-images.githubusercontent.com/39968564/44423146-b4e03680-a55b-11e8-805f-c27a3d5c4ce5.jpg)

**Comment by vasturiano** [comment]
Hi @feliperfpereira, the thickness of the rings is calculated so that the area of the slices are proportional to the data they are representing. They decay outwards in a quadratic manner.

This pattern is also persistent across all zoom levels.

If the radius of the rings would be adjustable, they would no longer be guaranteed to be proportional.

**Comment by shaik305** [comment]
> Is there any way to resize the me main(first) node, I want to give more height to children's and less to main node
> ![sinergytech - ocs - google chrome](https://user-images.githubusercontent.com/39968564/44423146-b4e03680-a55b-11e8-805f-c27a3d5c4ce5.jpg)

Any update on this ?

**Comment by vasturiano** [comment]
@shaik305 please see the description above as to the why of that design decision, to not introduce visual distortion.

**Comment by yj000018** [comment]
Fully understand the design choice, however in some case the point is more to represent tree of data/categories and less proportion of numbers... having both options would be good!! (Proportionate to data value - quadratic, or flexible sizes)

**Comment by veloware** [comment]
Maybe I'm missing something, but I don't see how it makes sense to have to root node be sized proportionally to the data within in it, does that mean the more data you have, the larger the (single) root node is?  That doesn't make sense to me :/

**Comment by vasturiano** [comment]
@veloware another option you have available which may suit your use case is to remove the root node altogether from the representation. You can do that with `.excludeRoot(true)`.

**Comment by veloware** [comment]
Yea I have tried that, though its the same problem on the next level.  In my case the next level down from root _can_ be a single node again.

**Comment by vasturiano** [comment]
I've added a configuration method for this: `radiusScaleExponent`. It allows to set the exponent of the power scale used to calculate the multi-layered rings thickness.
By default it is set to `0.5` for backwards compatibility and to preserve area.

Some examples of usage:

Default: Quadratic (`0.5`):
![Screenshot 2020-07-07 at 11 06 08](https://user-images.githubusercontent.com/6784226/86824076-80d46880-c042-11ea-8622-494dcde29656.png)

Linear (`1`):
![Screenshot 2020-07-07 at 11 06 37](https://user-images.githubusercontent.com/6784226/86824002-6a2e1180-c042-11ea-9083-01db949f36f2.png)

Exponential (`2`):
![Screenshot 2020-07-07 at 11 07 13](https://user-images.githubusercontent.com/6784226/86824045-76b26a00-c042-11ea-88c1-be0f848f53aa.png)
