### ISSUE TITLE
Updating chart data updates tooltips correctly but not labels

### ISSUE THREAD

**Issue by CrypticGuru** [vasturiano/sunburst-chart#12]
I create a new chart like so: `myChart = Sunburst().data(original_data)(the_element)`, and everything works as expected.

However, when I subsequently call `myChart.data(new_data)` the labels continue to represent the values from `original_data`, BUT the tooltips DO update to represent the values from `new_data`.

**Comment by vasturiano** [comment]
@CrypticGuru thanks for the report. Yes, you're right, there was a bug in the module in which the data updates weren't propagating to the labels.
This is now fixed, so if you use the latest version, you shouldn't experience the issue anymore.
