### ISSUE TITLE
How to clear out the sunburst chart

### ISSUE THREAD

**Issue by cjkirk09** [vasturiano/sunburst-chart#13]
I am trying to clear out the sunburst chart, but it won't.
The data comes from an api call, and if it gets back no data, I want it to be empty.

The data updates fine when I have more data, but not when I have no data.
I have tried the following
```
this.hierarchySunburstChart.data(null)  // doesn't update
                        
this.hierarchySunburstChart.data({})  
// turns black and produces a lot of console errors saying:
// ERROR TypeError: Cannot read property 'toString' of undefined
                        
this.hierarchySunburstChart.data() // doesn't update
                        
this.hierarchySunburstChart.data(undefined) // doesn't update
```
I am using v1.2.2 in Angular 5 on Chrome.

**Comment by JP-Basson** [comment]
While I don't think it's the correct solution. I am setting the div ID to inner html to empty before I redo the data

document.getElementById('chart').innerHTML = '';

**Comment by vasturiano** [comment]
@JP-Basson these calls all do the same, return the current value of `data`:
```
.data()
.data(null)
.data(undefined)
```

If you wish to set new data, your object must have at least one element (the root). If you wish for nothing to be shown, I'd suggest something like:
```
.data({ name: '', color: 'rgba(0,0,0,0)' })
```

Let me know if that works for you.

**Comment by cjkirk09** [comment]
@vasturiano That worked great. Thanks!
