### ISSUE TITLE
Feature request - labels vertical layout when it does not fit horizontally

### ISSUE THREAD

**Issue by Vity01** [vasturiano/sunburst-chart#15]
Current version just shows labels in horizontal position. It would be nice to add detection to show labels vertically if possible. 
Similar to highcharts sunburst chart - please see https://www.highcharts.com/demo/sunburst

**Comment by vasturiano** [comment]
Nice suggestion @Vity01, thanks! I'll keep the issue open as it needs implementation, when I have a bit of time. :)

**Comment by Vity01** [comment]
Great!
I have also another idea. 
If the name is too long , eg. : veryVeryLongTitle sometimes it might me useful to generate shorter name: `very..Title` or similar like that (based on the maximum count of characters they can fit with current font into area).

**Comment by hamburml** [comment]
I would love this!
