### ISSUE TITLE
Responsive chart

### ISSUE THREAD

**Issue by matiasmicheletto** [vasturiano/sunburst-chart#17]
I need to fit the chart inside a responsive div (materialize cards). Just found workarounds for making d3 svg responsive but cannot figure out how to replicate this with the sunburst chart.

**Comment by vasturiano** [comment]
@matiasmicheletto you can add the responsive behaviour to a container element, and dynamically control the chart dimensions using the `.width()` and `.height()` methods.

**Comment by matiasmicheletto** [comment]
> 
> 
> @matiasmicheletto you can add the responsive behaviour to a container element, and dynamically control the chart dimensions using the `.width()` and `.height()` methods.

Thank you for your answer. Do you have an example to show how to achieve this? I tried:
`window.addEventListener("resize", function(){
        Sunburst()
            .data(myData)
            .size('size')
            .color('color')
            .width(window.innerWidth*0.8)
            .height(window.innerHeight*0.8)
            (document.getElementById('chart'));
    });`

but nothing happens

**Comment by vasturiano** [comment]
@matiasmicheletto you could try with a convenience library like https://github.com/wnr/element-resize-detector. But it's beyond the scope of `sunburst-chart`.

Also, you don't need to re-instantiate the whole component on resize. This is better:
```
const myChart = Sunburst()
    .data(myData)
    .size('size')
    .color('color')
    (document.getElementById('chart'));

window.addEventListener("resize", function() { 
    myChart
      .width(window.innerWidth*0.8)
      .height(window.innerHeight*0.8);
});
```

**Comment by Githamza** [comment]
How to set the `width` and `height` to `100%` ?

**Comment by vasturiano** [comment]
@Githamza please see reply above. You can use a responsive library for that. 👍

**Comment by Githamza** [comment]
The respond treats width and height size depending on windows size. I'm looking to have 100% width of it's parent not all window

**Comment by vasturiano** [comment]
Using for example the lib above [element-resize-detector](https://github.com/wnr/element-resize-detector) you can extract element dimensions (`width`, `height`). You can just use fractions of those absolute values if you'd like, i.e. `myChart.width(parentWidth * 0.5)`.

**Comment by YashCerebulb** [comment]
@vasturiano Your solution for responsive chart is working fine..
but what if we have resizable div and at that time resize event is not thrown so how can we make chart responsive according to div resize not window ?
thanks in advance.

**Comment by vasturiano** [comment]
@YashCerebulb I believe `element-resize-detector` should be able to respond to individual element size changes, not just `window`, so you should be able to make it work for your case. It all depends on what element you choose to "monitor".
