### ISSUE TITLE
d.value in the tooltip() returns value of the nodes, not the sum of value of it's children

### ISSUE THREAD

**Issue by sterkhedkar** [vasturiano/sunburst-chart#18]

**Comment by vasturiano** [comment]
@sterkhedkar the second argument of `tooltipContent(data, node)` gives you access to the total summed value. See this example for usage:
https://github.com/vasturiano/sunburst-chart/blob/master/example/sort-by-size/index.html#L39

**Comment by sterkhedkar** [comment]
@vasturiano  Thanks a lot! For saving my butt! Kudos :)
