### ISSUE TITLE
Editable label background colors

### ISSUE THREAD

**Issue by NextiaDev** [vasturiano/sunburst-chart#22]
As of right now, all labels have a white background that can interfere with the beautiful sunburst design. It would be amazing if you could choose to ignore the background or give it a custom color

**Comment by vasturiano** [comment]
@NextiaDev you can change that by applying some CSS overrides. Look here for the relevant rules:
https://github.com/vasturiano/sunburst-chart/blob/master/src/sunburst.css#L14

For example doing the following will hide the white background:
```
.sunburst-viz text .text-contour {
  display: none;
}
```

**Comment by NextiaDev** [comment]
Thanks for the response! I have another question. Is there a way to increase the tooltip size? The categories are overflowing (Parent > Children > etc ) when it reaches the fourth level.

**Comment by vasturiano** [comment]
@NextiaDev thanks for reporting that. To fix it from the consumer side, you can CSS override just like above, this css property:
https://github.com/vasturiano/sunburst-chart/blob/master/src/sunburst.css#L39

**Comment by EgilSandfeld** [comment]
> @NextiaDev you can change that by applying some CSS overrides. Look here for the relevant rules:
> https://github.com/vasturiano/sunburst-chart/blob/master/src/sunburst.css#L14
> 
> For example doing the following will hide the white background:
> 
> ```
> .sunburst-viz text .text-contour {
>   display: none;
> }
> ```

Sorry, but where do you apply these overrides? In an external CSS file?

**Comment by vasturiano** [comment]
@EgilSandfeld yes for example. It all depends on how you apply CSS rules in your project.
