### ISSUE TITLE
how to get x , y position of node / arc / path while in update method to hide certain layers' nodes

### ISSUE THREAD

**Issue by githubdd7** [vasturiano/sunburst-chart#24]
I have changed radius, so that it shows only few donuts (layers) of sunburst, but because I change radius some node are intersecting with svg boder, I wanted to hide those nodes.

How can I do that ?

I was trying to get bounding box for node after animation code in update method but it is giving me empty "d" attribute of path. "d" attribute of path updates after running everything like it completes rendering of page.

I was trying this 
```allSlices.select('path.main-arc').filter(d => d.data.name === 'name1').node().getBBox()``` in update method after this line 
```
allSlices.select('path.main-arc').transition(transition)
      .attrTween('d', d => () => state.arc(d))
      .style('fill', d => colorOf(d.data, d.parent));
```
but it gives me position of very initial place, like it is not rendered yet.

If I can get position of node, then I can hide node based on location of node.

Also, can you explain, how animation works here in sunburst code, for example
```
// Entering + Updating
    const allSlices = slice.merge(newSlice);

    allSlices.style('opacity', 1);

    allSlices.select('path.main-arc').transition(transition)
      .attrTween('d', d => () => state.arc(d))
      .style('fill', d => colorOf(d.data, d.parent));

    allSlices.select('path.hidden-arc').transition(transition)
      .attrTween('d', d => () => middleArcLine(d));

    allSlices.select('.path-label')
      .transition(transition)
        .styleTween('display', d => () => state.showLabels && textFits(d) ? null : 'none');

    // Ensure propagation of data to children
    allSlices.selectAll('text.path-label').select('textPath.text-contour');
    allSlices.selectAll('text.path-label').select('textPath.text-stroke');

    allSlices.selectAll('text.path-label').selectAll('textPath')
      .text(d => nameOf(d.data));
```

Thank You,

**Comment by vasturiano** [comment]
@githubdd7 it's not clear to me what you're trying to achieve. Could you make an online example reproducing your issue with this module, if there is an issue?

**Comment by pattarmanjunath50** [comment]
Hi,
I wanted to know is there any way we can show only selected labels in the sunburst-chart. If yes, please help

**Comment by pattarmanjunath50** [comment]
Sorry to bother you I got it in your documentation. Thanks
