### ISSUE TITLE
Remove max-width: 320px from .sunburst-tooltip CSS class

### ISSUE THREAD

**Issue by shufeilei** [vasturiano/sunburst-chart#25]
The translucent black background is too short for the breadcrumb text that exceeds 320px.

Can we remove `max-width: 320px` from the .sunburst-tooltip CSS class?

Thank you for creating this!

**Comment by vasturiano** [comment]
@shufeilei you can CSS override that style rule from your side, by doing:
```
.sunburst-tooltip {
  max-width: none;
}
```

**Comment by shufeilei** [comment]
@vasturiano i was trying to use this method to change the tooltip width, but i am running into problems with the webpack setup. i will figure out how to do the overwrite. thanks!
