### ISSUE TITLE
Skip the Root node

### ISSUE THREAD

**Issue by shufeilei** [vasturiano/sunburst-chart#26]
**Is your feature request related to a problem? Please describe.**
In my project, the root node does not serve any functional purpose. Is there a way to skip the root node?

**Comment by Abazidou** [comment]
I also need to hide it. Thanks.

**Comment by vasturiano** [comment]
I've just added a new prop: `excludeRoot` which you can set to `true` if you wish to hide the root layer.

Make sure to use the latest version: `1.6.0`.

**Comment by shufeilei** [comment]
thanks for implementing this. this is fantastic. could you also remove the "root" level from the breadcrumb in the tooltip? thanks!

**Comment by Abazidou** [comment]
Thanks!

**Comment by vasturiano** [comment]
@shufeilei glad it's useful. The tooltip has been corrected in `v1.7.0`.
