### ISSUE TITLE
Set fixed value for diameter (or radius) of figure as whole

### ISSUE THREAD

**Issue by githubdd7** [vasturiano/sunburst-chart#27]
We would like to use the widget as part of a dashboard but want to specify a fixed size for it to occupy while minimizing white space. 

It's unclear how to achieve a fixed radius for the circle as a whole by specifying max radius for a given level, especially because the radius for each levels scales (which is appreciated). 

Ideally we'd like to specify the total radius and have the individual levels' radii inferred based on that (the total radius) and the shape of our data.

**Comment by vasturiano** [comment]
@githubdd7 you can set the `width` and `height` values. The chart's diameter will be the smallest of those two values.

**Comment by githubdd7** [comment]
Thanks you for the fast reply - I realize now that I should've noted that I'm also using the filter method to only display a fixed number of levels/depth. When doing that the chart diameter seems to still be set using the total number of levels, which results in a lot of white space/smaller sunburst - any suggestions on how to maximize the amount of space used?

The code to illustrate how we're displaying a fixed depth is below:
```
const slice = state.canvas.selectAll('.slice')
      .data(
        state.layoutData
          .filter(d => // Show only slices with a large enough angle
            d.x1 >= focusD.x0
            && d.x0 <= focusD.x1
            && (d.x1 - d.x0) / (focusD.x1 - focusD.x0) > state.minSliceAngle / 360
            && d.depth < (focusD ? (focusD.depth ? focusD.depth + levelsToDisplay : 4) : 4)
          ),
        d => d.id
      );
```
With levels to display = 4 in our case

**Comment by vasturiano** [comment]
@githubdd7 I just added a new prop to the module: `.maxLevels(<number>)`. This should allow you to configure the chart like you intend.

Make sure to switch to the latest version: `1.5.0`.

**Comment by githubdd7** [comment]
It works ! Thank You So Much !
