### ISSUE TITLE
Cannot load "<script src="//unpkg.com/sunburst-chart"></script>"

### ISSUE THREAD

**Issue by karkato** [vasturiano/sunburst-chart#3]
Hello, until this afternoon, i was using this script for work and since then, i can't load it again to use it. 
On my bowser network i can see that the script page return a 404 not found.
Can you help me or confirm that the script is dead.

Thx

**Comment by vasturiano** [comment]
@karkato that may have been a temp glitch with the connection to unpkg. Can you confirm that you can load this example correctly: https://vasturiano.github.io/sunburst-chart/example/flare/

**Comment by karkato** [comment]
Hello, i can load the example correctly. Thx =)
