### ISSUE TITLE
identify center node / circle and make it always fill with transparent color 

### ISSUE THREAD

**Issue by githubdd7** [vasturiano/sunburst-chart#32]
**Is your feature request related to a problem? Please describe.**
I wanted to put text at very center node / circle every time even when you zoom in.

**Describe the solution you'd like**
So, I was thinking to make center node / circle transparent and put div there with some text.

**Describe alternatives you've considered**
There is also showLabels method but not sure, how I can use it.

**Comment by vasturiano** [comment]
@githubdd7 you can keep track of when the chart changes focus, by attaching a listener to the `.onClick(node => ...)` event. You can also extract the current node in focus simply by calling `.focusOnNode()` without any arguments.

If you know the node that is currently in focus, you know that the node in the center is its parent, which you can access by doing `node.__dataNode.parent.data` (if `node.__dataNode.parent` is `null` you're at the top level).

Once you know which node is at the center, you can style it selectively whichever way you wish by calling the usual accessor methods like `.color(node => ...)` or `.label(node => ...)`.

**Comment by githubdd7** [comment]
Thank You @vasturiano
