### ISSUE TITLE
Number formatting of tooltip 

### ISSUE THREAD

**Issue by nik911sc** [vasturiano/sunburst-chart#34]
**Is your feature request related to a problem? Please describe.**

Not so much a problem but an enhancement.

**Describe the solution you'd like**

The ability to apply a number format. As a minimum to limit number display to 2 decimal places. Ideally the ability to apply currency format with comma's per '000.

**Describe alternatives you've considered**

N/A

**Additional context**

I am not sure if there is a rounding/trimming issue within the d3 code as all my source data is limited to 2 decimal places yet various slices output show 10+ decimal places.

**Comment by vasturiano** [comment]
@nik911sc thanks for reaching out.

This module should not be doing any number formatting in the tooltip. You are in full control of what data/formatting you show in the tooltip via the `.tooltipContent(node => ...)` method.

**Comment by nik911sc** [comment]
Thanks for the follow up. Much appreciated.
