### ISSUE TITLE
make method for onClickCanvas

### ISSUE THREAD

**Issue by githubdd7** [vasturiano/sunburst-chart#35]
**Is your feature request related to a problem? Please describe.**
Yes, I need to do some extra things when user clicks on canvas/white background. Currently, I have to modify original sunburst code since there is no method exposed yet for clicking on canvas.

**Describe the solution you'd like**
Make public method for onClickCanvas

**Describe alternatives you've considered**
Modify inside code of sunburst to do some extra things when user clicks on canvas/background.

**Comment by vasturiano** [comment]
@githubdd7 for this you can just capture click events on your parent DOM element. The background click events should be bubbling up the DOM.

**Comment by githubdd7** [comment]
Ok, Thanks.
