### ISSUE TITLE
Methods for mouseover and mouseleave for sunburst node

### ISSUE THREAD

**Issue by githubdd7** [vasturiano/sunburst-chart#36]
**Is your feature request related to a problem? Please describe.**
I wanted to do certain things/actions when user hover over to particular node of sunburst and remove those things/actions when user leaves that node (i.e. move out mouse from that node)

**Describe the solution you'd like**
Methods for mouseover, mouseenter, mouseleave for sunburst widget for node.

**Describe alternatives you've considered**
Modify inner methods to achieve above request.

**Additional context**
Also, will I get color information when I hover over to particular node by calling color() method ?

**Comment by vasturiano** [comment]
@githubdd7 I just added a new method: `onHover` that lets you control these interactions.
