### ISSUE TITLE
calling focusOnNode method causes JavaScript error

### ISSUE THREAD

**Issue by githubdd7** [vasturiano/sunburst-chart#37]
**Describe the bug**
I created sunburst object, and later on I use that sunburst object to call focusOnNode method.
But it gives me JavaScript error. It gives error at line 146: https://github.com/vasturiano/sunburst-chart/blob/master/src/sunburst.js#L146 which says state.focusOnNode have no/null __dataNode property.

**To Reproduce**
1. ```someButton.on('click', (d: any) => this.sunburst.focusOnNode(d.data.__dataNode); )```
where ```d``` is following:
![image](https://user-images.githubusercontent.com/50960461/63720643-a89d5200-c81d-11e9-9bf5-5d4d3533e3a6.png)
2. which causes line 146 of https://github.com/vasturiano/sunburst-chart/blob/master/src/sunburst.js#L146 to say that ```state.focusOnNode``` 's ```__dataNode``` has undefined which means ```state.focusOnNode.__dataNode.y0``` gives error.
![image](https://user-images.githubusercontent.com/50960461/63720686-be127c00-c81d-11e9-9945-8e07f6dd3b9d.png)
3. even if I call with just ```this.sunburst.focusOnNode(d);``` , it still gives same error.

**Expected behavior**
No JavaScript error and sunburst should focus on node which I pass to ```focusOnNode``` function.

**Screenshots**
Provided above

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 76

**Comment by vasturiano** [comment]
@githubdd7 yes, to `focusOnNode` you should be passing the node object itself (`d.data` in your case), not the inner layout object (`__dataNode`).
