### ISSUE TITLE
How to use onNodeClick

### ISSUE THREAD

**Issue by karkato** [vasturiano/sunburst-chart#4]
How can I use onNodeClick method. From the README it's not clear. Can I catch the click event on nodes?

**Comment by vasturiano** [comment]
@karkato below is an example of using the `onNodeClick` method. This actually reproduces the default behavior of zooming to a node on click:
```
myChart
  .onNodeClick(node => {
    myChart.focusOnNode(node);

    // do other operations with node
  })
```

**Comment by karkato** [comment]
Ok, thx. I have a last question, i'm using the unpkg script but i want to have the sunburst-chart on my own server. Do you have any ideas on how i can do it ?

**Comment by vasturiano** [comment]
@karkato if you are using it in a node environment, you probably want to consume from the commonJS  version of the package (`dist/sunburst-chart.common.js`). This should happen automatically if you install the module locally (`npm install sunburst-chart`) and import it using require (`const Sunburst = require('sunburst-chart');`).

**Comment by karkato** [comment]
Thank you for you answers. Have a good day =)

**Comment by pattarmanjunath50** [comment]
Hi, 
Is it possible to listen to a right click (contextmenu) event on a node?

**Comment by pattarmanjunath50** [comment]
Thanks for replying...
How can I access the respective node's element so that I can add an event listener for contextmenu on that element? Please help..

**Comment by Isuru40** [comment]
I used this chart as a navigation model. This was my implementation.

     this.myChart.onNodeClick(node => {
      this.myChart.focusOnNode(node);
      if(node.uuid =="1234"){
        console.log("item"+node.uuid);
        this.router.navigateByUrl('dash');
      }
          })

routing is worked fine. I configured tooltip   
     this.myChart.tooltipTitle(d=>d.name)

when routing happen into that page ,tooltip still appear  on that page also. Could you please let me know the solution to avoid that issue.

**Comment by Isuru40** [comment]
I have found a way.
in sunburst-chart.module.js 

    var newSlice = slice.enter().append('g').attr('class', 'slice').style('opacity', 0).on('click', function (d) {
      event.stopPropagation();
      state.tooltip.remove();
      (state.onClick || _this2.focusOnNode)(d.data);

just add the **state.tooltip.remove();**  then after route tooltip won't display on new location
