### ISSUE TITLE
Problem with "circularly references itself."

### ISSUE THREAD

**Issue by hmartim** [vasturiano/sunburst-chart#48]
The compiler is identifing this supposed problem:

ERROR in ../node_modules/sunburst-chart/dist/sunburst-chart.d.ts:75:6 - error TS2456: Type alias 'SunburstChartInstance' circularly references itself.

75 type SunburstChartInstance = SunburstChartGenericInstance<SunburstChartInstance>;

**Comment by vasturiano** [comment]
@hmartim you should update TS to a recent version. I believe this was recently fixed.
https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-rc/#more-recursive-type-aliases
