### ISSUE TITLE
showTooltip false throws Uncaught TypeError

### ISSUE THREAD

**Issue by veloware** [vasturiano/sunburst-chart#53]
**Describe the bug**
when setting showTooltip to false - `.showTooltip(false)` the tooltips are correctly removed but there is a new `Uncaught TypeError - state.showTooltip is not a function` error on the console for ever hover event.

I have also tried `.showTooltip(() => false)` as per the docs for passing a function as the arg, but Typescript is complaining that a function is not assignable to boolean.  I can see `showTooltip(show: boolean): ChainableInstance;` in the types file, so I assume it is expecting a boolean.

**To Reproduce**
1. set `.showTooltip(false)`
2. hover over a segment
3. notice TypeError on console.

**Expected behavior**
An error shouldnt be in the console.  (And does the docs need updated to reflect the boolean arg and not a function?)

**Screenshots**
<img width="467" alt="Screenshot 2020-06-27 at 11 09 08" src="https://user-images.githubusercontent.com/61578546/85919832-be790a80-b866-11ea-97a7-745b23c5418b.png">

**Desktop (please complete the following information):**
 - OS: ios
 - Browser chrome

**Comment by vasturiano** [comment]
@veloware thanks for the report.

I've fixed the TypeScript definition to match the correct expectation. It should be set to a node accessor function that returns a `boolean`. 👍
