### ISSUE TITLE
Tooltip not removed if refresh

### ISSUE THREAD

**Issue by luipir** [vasturiano/sunburst-chart#56]
**Describe the bug**
I've sunburst-chart integrated in a Grafana panel via a custom plugin:
https://github.com/luipir/GaliciaSustentable_deployment/blob/master/dashboards/luipir-sunburst-panel/src/SunburstPanel.tsx

if I select a voice in a dropdown menu overlapping the canvas, appear the tooltip where I clicked as the screenshot [1].
 The tooltip is not removed if I reset the sunburst removing and recreating it as in screenshot [2]

IMHO would make sense:
1) remove al sunburst-tooltip div elements during init
2) better, add the tooltip to the sunburst hierarchy 

**To Reproduce**
well reproducible only if a menu overlap the canvas. Steps to reproduce the behavior:
1. Open the menu overlapping the canvas
2. select an element that overlap the chart
3. after click, the tooltip appear (becaosue of move event)
4. Due to reset of sunburst, the tooltip does not disappear

**Expected behavior**
No tooltip would remain

**Screenshots**
[1] ![Screenshot from 2020-07-17 11-00-20](https://user-images.githubusercontent.com/3344634/87768668-cd772b00-c81c-11ea-8ad7-30ba4fec0900.png)
[2] ![Screenshot from 2020-07-17 10-57-28](https://user-images.githubusercontent.com/3344634/87768671-cea85800-c81c-11ea-8fcb-4bd1e8638797.png)

**Desktop:**
 - OS: Ubuntu
 - Browser chrome, firefox
 - Version chrome: Version 83.0.4103.116 (Official Build) (64-bit) - firefox: 78.0.2 (64-bit)

**Comment by luipir** [comment]
probably better to set them hierarchically down "sunburst-viz" div

**Comment by luipir** [comment]
temporarly solved outside sunburst-chart with:

const tooltips = document.getElementsByClassName('sunburst-tooltip');
_.each(tooltips, (tooltip: HTMLDivElement) => {
tooltip.remove()
})

before rendering new chart

**Comment by vasturiano** [comment]
Thanks for the report @luipir.

I've changed the tooltip DOM structure so that they're nested under the chart element instead of directly on the body.
I think this should fix your issue as they will be automatically removed when the main DOM element is unmounted.

Fixed in `v1.11.2`.

**Comment by luipir** [comment]
tnx @vasturiano
