### ISSUE TITLE
Is there a way to align labels straight alongside the radius?

### ISSUE THREAD

**Issue by demian85** [vasturiano/sunburst-chart#64]
I want to position the labels differently but honestly, I'm not sure if that achievable via CSS & SVG. It should. Any ideas on how to orient the text straight alongside the circle radius? Thanks.

**Comment by vasturiano** [comment]
@demian85 that's related to [this issue](https://github.com/vasturiano/sunburst-chart/issues/15).

Long story short, it's not currently supported. The label positioning computation needs to be implemented to support both radial and circular labels.

**Comment by vasturiano** [comment]
@demian85 I've just added a `labelOrientation` setting, that will allow you to orient the labels radially, by doint:
```js
.labelOrientation('radial')
```

By default it picks the most suitable orientation for the particular arc / text.

Please try it with `v1.12.0`.

**Comment by demian85** [comment]
Thanks for your addition, but I have a new issue now. As you can see, the text is not readable. It is white and was perfectly readable with arc orientation. Any thoughts?

**Comment by demian85** [comment]
Looks like removing the fill property for class `.tru-treasury .sunburst-viz text` does the trick
