### ISSUE TITLE
Stroke arc color

### ISSUE THREAD

**Issue by JREGN** [vasturiano/sunburst-chart#65]
Hi ! 
Is it possible to set the stroke color of each arc like the fill color, depending on a function ?

Thanks !

**Comment by vasturiano** [comment]
Hi @JREGN, thanks for the feature request.

I've just added a new prop `strokeColor` that lets you customize the stroke per arc. Please try it with the latest version. 👍

**Comment by JREGN** [comment]
Thanks a lot !
