### ISSUE TITLE
Children size

### ISSUE THREAD

**Issue by JREGN** [vasturiano/sunburst-chart#66]
Hi, 

Is it possible to force children size to take 100% of their parent size ?
I try to play with [size] and [radiusScaleExponent] without success.

Thanks

**Comment by vasturiano** [comment]
@JREGN are you referring to the angular size of the nodes.

The angular size of a node is determined by the sum of the sizes of all its children, plus its own. So, if a node has only one child, and 0 own size, it will be as wide as its child.

**Comment by JREGN** [comment]
Thanks for your answer. I now understand.
