### ISSUE TITLE
Is it possible to make clicked node move strait to center ?

### ISSUE THREAD

**Issue by cedric-g** [vasturiano/sunburst-chart#67]
Hello :)
I would like to know if there is a way or option to make the clicked node move strait to center instead of moving to 1st ring ?

**Comment by vasturiano** [comment]
@cedric-g that's not really possible, because the central node is reserved for the "zoom out" one level functionality. If you'd do that you'd lose the ability to navigate back up the tree.

**Comment by cedric-g** [comment]
I understand the center is reserved for the "zoom out" and that's fine. What I mean by going to center is make the node "disapear", I mean not setting it as full first ring but get directly its chrildren as first ring.

**Comment by vasturiano** [comment]
@cedric-g I don't think that behaviour is currently possible. The closest you'll be able to get is to set `.centerRadius(0)` but that actually hides the parent node, not the current node.

**Comment by cedric-g** [comment]
Ok thanks.
