### ISSUE TITLE
Labels not updating on new data

### ISSUE THREAD

**Issue by paulboichat** [vasturiano/sunburst-chart#74]
**Describe the bug**
When a chart's data is updated via .data() the visualisation is updated to reflect the new detail but the labels aren't refreshed until the onClick is triggered

**To Reproduce**
1. Initialise a Sunburst with datasetA
2. On an lifecycle event (clicking a link in the example) call sunburst.data with datasetB

**Expected behavior**
The chart should update to reflect the new data including the labels

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari

** Example **

`
 const data = {
      name: 'main',
      color: 'magenta',
      children: [{
        name: 'a',
        color: 'yellow',
        size: 1
      },{
        name: 'b',
        color: 'red',
        children: [{
          name: 'ba',
          color: 'orange',
          size: 1
        }, {
          name: 'bb',
          color: 'blue',
          children: [{
            name: 'bba',
            color: 'green',
            size: 1
          }, {
            name: 'bbb',
            color: 'pink',
            size: 1
          }]
        }]
      }]
    };

const data1 = {
      name: 'NEW',
      color: 'magenta',
      children: [{
        name: 'A',
        color: 'yellow',
        size: 10
      },{
        name: 'B',
        color: 'red',
        children: [{
          name: 'BA',
          color: 'orange',
          size: 1
        }, {
          name: 'BB',
          color: 'blue',
          children: [{
            name: 'BBA',
            color: 'green',
            size: 1
          }, {
            name: 'BBB',
            color: 'pink',
            size: 1
          }]
        }]
      }]
    };  

const sunburst = Sunburst()
      .data(data)
      .size('size')
      .color('color')
      .radiusScaleExponent(1)
      (document.getElementById('chart'));
      
const toggleData = () =>{
          sunburst.data(data1)
}
`

**Comment by vasturiano** [comment]
Thanks for the example @paulboichat. There was an issue with propagating data changes to the labels. I've put in a fix, could you please try with the latest version and let me know if it fixes your problem?

**Comment by paulboichat** [comment]
Amazing. All sorted. Thanks!
