### ISSUE TITLE
Allowing controls for styles

### ISSUE THREAD

**Issue by artt** [vasturiano/sunburst-chart#77]
**Is your feature request related to a problem? Please describe.**
I'd like to have some controls over the width and height of the chart. Right now the style for svg element is applied in-line.

**Describe the solution you'd like**
Allow styles to be passed into the method. For example
```js
myChart.style({width: '100%'})
```

**Describe alternatives you've considered**
Right now I have to put the following in css:
```css
.sunburst-viz > svg {
  width: 100% !important;
}
```
This is not ideal.

**Comment by vasturiano** [comment]
@artt to make the component responsive you can simply use a 3rd party lib dedicated to this purpose, f.e. [element-resize-detector](https://github.com/wnr/element-resize-detector).

**Comment by artt** [comment]
Thanks! Just thought out-of-the-box support for styling would be easier. That's up to you though. Will close this issue for now :)
