### ISSUE TITLE
Using focusOnNode causes an uncaught TypeError

### ISSUE THREAD

**Issue by dcermak** [vasturiano/sunburst-chart#79]
**Describe the bug**

I tried to experiment with the `focusOnNode` setter, but setting this to any value causes:
```
Uncaught TypeError: Cannot read property 'y0' of undefined
    at Function.update (sunburst.js:153)
    at kapsule.module.js:129
    at later (index.js:27)
```
which comes from this line:
```js
    const focusD =
      (state.focusOnNode && state.focusOnNode.__dataNode.y0 >= 0 && state.focusOnNode.__dataNode)
      || { x0: 0, x1: 1, y0: 0, y1: 1 };
```
as `state.focusOnNode` has no property `__dataNode`.

**To Reproduce**
1. Open https://github.com/vasturiano/sunburst-chart/blob/master/example/large-data/index.html
2. Add `.focusOnNode(n => {console.log(n); return n;})` to line 41
3. open the file in your browser
4. Nothing is displayed and the above exception is seen in the console

**Expected behavior**
No exception should occur

**Comment by vasturiano** [comment]
@dcermak thanks for reaching out.

The `focusOnNode` takes a node object, not a function. So, you should invoke it as
```js
myChart.focusOnNode(<node object in data you wish to zoom to>)
```
