### ISSUE TITLE
How to use this sunburst in React?

### ISSUE THREAD

**Issue by matter13311** [vasturiano/sunburst-chart#85]
How do I use this npm package with React?
`
import React from 'react'
import Sunburst from 'sunburst-chart';

return(
 < Sunburst/ >
)
`

I get an error saying Sunburst can't be used in JSX.

**Comment by vasturiano** [comment]
@matter13311 this is not a React component, thus you cannot use it directly in a React environment directly.
The manner to instantiate this module is specified in the [docs](https://github.com/vasturiano/sunburst-chart#quick-start), so you'll need to write a React wrapper around it if you want to use it in a JSX context. 

[react-kapsule](https://github.com/vasturiano/react-kapsule) offers a means to do that easily, but there are other ways you can achieve the same.

**Comment by hallundbaek** [comment]
Could you give an example with react-kapsule?

**Comment by vasturiano** [comment]
Something along these lines:
```js
import fromKapsule from 'react-kapsule';
import sunburstKapsule from 'sunburst-chart';

const Sunburst = fromKapsule(sunburstKapsule);
```

then use it in React:
```jsx
<Sunburst data={myData} />
```

**Comment by hallundbaek** [comment]
Thanks for the fast reply!

Your example was also my intuition but trying it out in yields the following typeerror:

```
Argument of type '(configOptions?: ConfigOptions | undefined) => SunburstChartInstance' is not assignable to parameter of type 'KapsuleClosure'.
Property 'resetProps' is missing in type 'SunburstChartGenericInstance<SunburstChartInstance>' but required in type 'KapsuleInstance'.ts(2345)
```

**Comment by vinicius-gregorio** [comment]
did you figured it out?

**Comment by hallundbaek** [comment]
No, I ended up not using react-kapsule. Just generated the chart and applied it to a div with an id, something to this effect:

```
export type SunburstLeaf = {
  name: string;
  size: number;
  color: string;
};

export type SunburstNode = {
  name: string;
  color: string;
  size: number; 
  children: (SunburstNode | SunburstLeaf)[];
};

interface SunburstElementProps {
  data: SunburstNode | undefined
}

export const SunburstElement = (props: SunburstElementProps) => {
  const { data } = props;
  
  useEffect(() => {
    if (data) {
      suburst()
        .data(data)
        .label("name")
        .size("size")
        .height(200)
        .width(200)
        .color("color")(document.getElementById("chart")!);
    }
  }, [data]);
  
  return <div id="chart" />
}
```

And some extra logic to delete the children of the div when `data` changes.
