### ISSUE TITLE
Hide node are not working properly

### ISSUE THREAD

**Issue by koushikchattaraj** [vasturiano/sunburst-chart#92]
I am facing a issue in the last node of the graph where the last entity of the previous fold is showing as a slim line between the after fold.
<img width="960" alt="Screenshot 2022-07-11 153115" src="https://user-images.githubusercontent.com/49994010/178240399-4ce79fb5-9ee1-4565-a25d-a9355a6e39f0.png">
<img width="960" alt="Screenshot 2022-07-11 153144" src="https://user-images.githubusercontent.com/49994010/178240420-e9636efb-de9c-4ab2-9fb7-49b909c274a8.png">
<img width="960" alt="Screenshot 2022-07-11 153228" src="https://user-images.githubusercontent.com/49994010/178240440-113910e5-dfdd-437c-81e8-933c271580e2.png">

If you check on 3rd Picture when I hover on the line Its show me the previous node Data. If I click on the line then its redirect to another Node.

**Comment by vasturiano** [comment]
Thanks for your report @koushikchattaraj. There was a small bug in the overlapping check of the nodes that was incorrectly keeping direct neighbours of the node in focus (`<=` vs `<`). This is now fixed and a patch published.

**Comment by koushikchattaraj** [comment]
Thanks Vasturiano.
