### ISSUE TITLE
How to stop onClick from overriding the default focusOnNode method?

### ISSUE THREAD

**Issue by vivekthapliyal4** [vasturiano/sunburst-chart#96]
`import React, { useEffect, useRef } from "react";
import { users } from "./users";
import Sunburst from "sunburst-chart";
import * as d3 from "d3";

const SunBurst = () => {
  console.log(users);
  const color = d3.scaleOrdinal(d3.schemeAccent);
  useEffect(() => {
    Sunburst()
      .data(users)
      .label("name")
      .size("cases")
      .onClick((node) => console.log(node))
      .color((d, parent) => color(parent ? parent.data.name : null))
      .tooltipContent((d, node) => `Size: <i>${node.value}</i>`)(
      document.getElementById("chart")
    );
  }, []);

  return <div id="chart"></div>;
};

export default SunBurst;
`

**Comment by vivekthapliyal4** [comment]
@vasturiano

**Comment by vasturiano** [comment]
@vivekthapliyal4 please see https://github.com/vasturiano/sunburst-chart/issues/94#issuecomment-1219579780.

**Comment by vivekthapliyal4** [comment]
> @vivekthapliyal4 please see [#94 (comment)](https://github.com/vasturiano/sunburst-chart/issues/94#issuecomment-1219579780).

Thanks man
